# Generated by Django 3.2 on 2023-08-31 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=50)),
                ('bus_type', models.CharField(max_length=50)),
                ('bus_source', models.CharField(max_length=50)),
                ('bus_destination', models.CharField(max_length=50)),
                ('bus_departure_time', models.TimeField()),
                ('bus_arrival_time', models.TimeField()),
                ('bus_fare', models.IntegerField()),
                ('bus_date', models.DateField()),
                ('plate_number', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BusSeatLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_seats', models.IntegerField()),
                ('seat_type', models.CharField(max_length=50)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('seat_label', models.CharField(max_length=50)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_image', models.ImageField(default='images/None/Noimg.jpg', upload_to='images/')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
        migrations.CreateModel(
            name='BusBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
                ('seats', models.ManyToManyField(to='bus.BusSeat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='BusAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bus.businfo')),
            ],
        ),
    ]
